name 'Jellyfish'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Jellyfish'
long_description 'Installs/Configures Jellyfish'
version '0.1.0'
