name 'Jellyfish'
maintainer 'Eagle Genomics Ltd.'
maintainer_email 'chef@eaglegenomics.com'
license 'Apache 2.0'
description 'Installs/Configures Jellyfish'
long_description 'Installs/Configures Jellyfish'
version '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'magic_shell'
